### ISSUE TITLE
Scala3Compiler fails when scalacOptions enables -Ysemanticdb

### ISSUE THREAD

**Issue by mlachkar** [mlachkar/scala-migrat3#24]
The error: CompilationUnit.source is null
```
[info]   java.lang.NullPointerException:
[info]   at dotty.tools.dotc.semanticdb.ExtractSemanticDB$.absolutePath$1(ExtractSemanticDB.scala:603)
[info]   at dotty.tools.dotc.semanticdb.ExtractSemanticDB$.write(ExtractSemanticDB.scala:606)
[info]   at dotty.tools.dotc.semanticdb.ExtractSemanticDB.run(ExtractSemanticDB.scala:48)
[info]   at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
[info]   at scala.collection.immutable.List.map(List.scala:246)
[info]   at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
[info]   at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
[info]   at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[info]   at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[info]   at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
```

When changing CompilationUnit.java with the code below, it doesn't fix the NullPointerException
```

import dotty.tools.dotc.util.SourceFile;
import scala.io.Codec;
import dotty.tools.dotc.util.SourceFile;
import dotty.tools.io.VirtualFile;
public class CompilationUnit {
  public String content;
  public String name; 
  public CompilationUnit(String name, String content) {
    this.name = name;
    this.content = content;
    this.source = new SourceFile(new VirtualFile(name, content.getBytes()), Codec.UTF8());
  } 
}
```

Right now, we filter scalac3Options to remove semanticdb
```
val modified = scala3CompilerOptions.filterNot(_ == "-Ysemanticdb")
```

**Comment by mlachkar** [comment]
solution `val modified = scala3CompilerOptions.filterNot(_ == "-Ysemanticdb")` should be enough
